# Generated by Django 4.0.1 on 2022-10-21 07:06

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dy_sales',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='sales编号')),
                ('shop', models.CharField(db_index=True, max_length=64, verbose_name='店铺')),
                ('now_date', models.DateField(db_index=True, verbose_name='日期')),
                ('deal_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='成交金额')),
                ('refund_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='退款金额')),
                ('freight', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='运费险')),
                ('budan_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='补单金额')),
                ('budan_yongjin', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='补单佣金')),
                ('extension_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='推广费用')),
                ('kf_re_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='客服返现')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'dy_汇总表',
                'verbose_name_plural': 'dy_汇总表',
                'db_table': 'dy_sales',
            },
        ),
        migrations.CreateModel(
            name='dy_sendcost',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='sendcost编号')),
                ('shop', models.CharField(db_index=True, max_length=64, verbose_name='店铺')),
                ('now_date', models.DateField(db_index=True, verbose_name='日期')),
                ('stylecode', models.CharField(db_index=True, max_length=32, verbose_name='款式编码')),
                ('send_number', models.IntegerField(db_index=True, verbose_name='发货数')),
                ('refund_number', models.IntegerField(db_index=True, verbose_name='退货数')),
                ('today_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='当天成本价')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'dy_发货退货数',
                'verbose_name_plural': 'dy_发货退货数',
                'db_table': 'dy_sendcost',
            },
        ),
        migrations.CreateModel(
            name='dy_sendgoods',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='sendgoods编号')),
                ('now_date', models.DateField(db_index=True, verbose_name='日期')),
                ('order_number', models.IntegerField(db_index=True, verbose_name='订单数')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'dy_日订单数',
                'verbose_name_plural': 'dy_日订单数',
                'db_table': 'dy_sendgoods',
            },
        ),
        migrations.CreateModel(
            name='Finace_Cost',
            fields=[
                ('stylecode', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, verbose_name='款式编码')),
                ('dy_cost', models.DecimalField(db_index=True, decimal_places=4, max_digits=20, verbose_name='抖音成本价')),
                ('tm_cost', models.DecimalField(db_index=True, decimal_places=4, max_digits=20, verbose_name='天猫成本价')),
                ('pdd_cost', models.DecimalField(db_index=True, decimal_places=4, max_digits=20, verbose_name='拼多多成本价')),
                ('jd_cost', models.DecimalField(db_index=True, decimal_places=4, max_digits=20, verbose_name='京东成本价')),
                ('tgc_cost', models.DecimalField(db_index=True, decimal_places=4, max_digits=20, verbose_name='淘工厂成本价')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': '成本价',
                'verbose_name_plural': '成本价',
                'db_table': 'Finace_Cost',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('Shop_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店铺编号')),
                ('Shop_name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='店铺名')),
                ('Shop_pallet', models.SmallIntegerField(choices=[[1, '拼多多'], [2, '天猫'], [3, '京东'], [4, '抖音'], [5, '淘工厂']], db_index=True, verbose_name='平台')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'db_table': 'app_shop',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('User_name', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='用户名')),
                ('User_email', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='邮箱')),
                ('User_password', models.CharField(db_index=True, max_length=16, verbose_name='密码')),
                ('User_face', models.ImageField(default='face_img/default_face.JPG', storage=system.storage.ImageStorage(), upload_to='face_img', verbose_name='头像')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'app_users',
            },
        ),
    ]
