# Generated by Django 4.0.1 on 2022-10-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Shop_pallet',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='店铺名'),
        ),
    ]
