# Generated by Django 4.0.1 on 2022-10-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cookies_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookies_all',
            old_name='shop',
            new_name='Shop',
        ),
    ]
