# Generated by Django 4.0.1 on 2022-10-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_shop_cookies_all_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies_all',
            name='cookies',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='cookies'),
        ),
    ]
