# Generated by Django 4.0.1 on 2022-10-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cookies_all_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies_all',
            name='cookies',
            field=models.CharField(db_index=True, max_length=10000, verbose_name='cookies'),
        ),
    ]
