# Generated by Django 4.0.1 on 2022-10-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cookies_all_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dy_sendcost',
            name='refund_number',
        ),
    ]
