# Generated by Django 4.0.1 on 2022-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dy_sendcost_refund_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dy_sendcost',
            name='refund_number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='退货数'),
        ),
        migrations.AlterField(
            model_name='dy_sendcost',
            name='send_number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='发货数'),
        ),
    ]
