# Generated by Django 4.0.1 on 2022-10-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_dy_sendcost_refund_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookies_all',
            name='id',
        ),
        migrations.AlterField(
            model_name='cookies_all',
            name='Shop',
            field=models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='dy_sendcost',
            name='refund_number',
            field=models.IntegerField(db_index=True, verbose_name='退货数'),
        ),
    ]
