# Generated by Django 4.0.1 on 2022-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_cookies_all_id_alter_cookies_all_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finace_tag_price',
            fields=[
                ('shop', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, verbose_name='店铺')),
                ('male_tag', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='男装吊牌价')),
                ('famale_tag', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='女装吊牌价')),
                ('child_tag', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='童装成本价')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': '吊牌价表',
                'verbose_name_plural': '吊牌价表',
                'db_table': 'finace_tag_price',
            },
        ),
    ]
