# Generated by Django 4.0.1 on 2022-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_finace_tag_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdd_sales',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='sales编号')),
                ('shop', models.CharField(db_index=True, max_length=64, verbose_name='店铺')),
                ('now_date', models.DateField(db_index=True, verbose_name='日期')),
                ('deal_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='成交金额')),
                ('refund_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='退款金额')),
                ('dd_scene', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='多多场景')),
                ('dd_search', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='多多搜索')),
                ('fxt', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='放心推')),
                ('qztg', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='全站推广')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='pdd_sendcost',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='sendcost编号')),
                ('shop', models.CharField(db_index=True, max_length=64, verbose_name='店铺')),
                ('now_date', models.DateField(db_index=True, verbose_name='日期')),
                ('stylecode', models.CharField(db_index=True, max_length=32, verbose_name='款式编码')),
                ('send_number', models.IntegerField(db_index=True, default=0, verbose_name='发货数')),
                ('refund_number', models.IntegerField(db_index=True, verbose_name='退货数')),
                ('today_price', models.DecimalField(db_index=True, decimal_places=4, max_digits=20, verbose_name='当天成本价')),
                ('today_tag', models.DecimalField(db_index=True, decimal_places=4, max_digits=20, verbose_name='当天吊牌价')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'pdd_发货退货数',
                'verbose_name_plural': 'pdd_发货退货数',
                'db_table': 'pdd_sendcost',
            },
        ),
        migrations.CreateModel(
            name='pdd_sendgoods',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='sendgoods编号')),
                ('shop', models.CharField(db_index=True, max_length=64, verbose_name='店铺')),
                ('now_date', models.DateField(db_index=True, verbose_name='日期')),
                ('order_number', models.IntegerField(db_index=True, verbose_name='订单数')),
                ('is_delete', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'pdd_日订单数',
                'verbose_name_plural': 'pdd_日订单数',
                'db_table': 'pdd_sendgoods',
            },
        ),
    ]
