# Generated by Django 4.0.1 on 2022-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_pdd_sales_options_alter_pdd_sales_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdd_sales',
            name='budan_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='补单金额'),
            preserve_default=False,
        ),
    ]
