# Generated by Django 4.0.1 on 2022-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_pdd_sales_budan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dy_sales',
            name='plat_cost',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='平台花费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dy_sendgoods',
            name='send_refund_cost',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='发货后退款成本'),
            preserve_default=False,
        ),
    ]
