# Generated by Django 4.0.1 on 2022-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_users_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dy_sales',
            name='plat_cost',
        ),
        migrations.AddField(
            model_name='dy_sales',
            name='collect_timeout',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='运费险'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dy_sales',
            name='fake_send_timeout',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='运费险'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dy_sales',
            name='send_timeout',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='运费险'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dy_sales',
            name='small_pay',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='运费险'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dy_sales',
            name='violation',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='运费险'),
            preserve_default=False,
        ),
    ]
