# Generated by Django 4.0.1 on 2022-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_dy_sales_plat_cost_dy_sales_collect_timeout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dy_sales',
            name='collect_timeout',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='揽收超时'),
        ),
        migrations.AlterField(
            model_name='dy_sales',
            name='fake_send_timeout',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='虚假发货超时'),
        ),
        migrations.AlterField(
            model_name='dy_sales',
            name='send_timeout',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='发货超时'),
        ),
        migrations.AlterField(
            model_name='dy_sales',
            name='small_pay',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='小额打款'),
        ),
        migrations.AlterField(
            model_name='dy_sales',
            name='violation',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='违规'),
        ),
    ]
