# Generated by Django 4.0.1 on 2022-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_users_user_erp_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_password',
            field=models.CharField(db_index=True, max_length=7000, verbose_name='密码'),
        ),
    ]
