# Generated by Django 4.0.1 on 2022-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_users_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_erp_cookies',
            field=models.CharField(blank=True, default=None, max_length=7000, null=True, verbose_name='当前用户聚水潭Cookies'),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_password',
            field=models.CharField(db_index=True, max_length=200, verbose_name='密码'),
        ),
    ]
