# Generated by Django 4.0.1 on 2022-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_users_user_erp_cookies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finace_cost',
            name='dy_cost',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=20, verbose_name='抖音成本价'),
        ),
        migrations.AlterField(
            model_name='finace_cost',
            name='jd_cost',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=20, verbose_name='京东成本价'),
        ),
        migrations.AlterField(
            model_name='finace_cost',
            name='pdd_cost',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=20, verbose_name='拼多多成本价'),
        ),
        migrations.AlterField(
            model_name='finace_cost',
            name='tgc_cost',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=20, verbose_name='淘工厂成本价'),
        ),
        migrations.AlterField(
            model_name='finace_cost',
            name='tm_cost',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=20, verbose_name='天猫成本价'),
        ),
    ]
