# Generated by Django 4.0.1 on 2022-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_finace_cost_dy_cost_alter_finace_cost_jd_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdd_day_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(db_index=True, max_length=64, verbose_name='店铺')),
                ('now_date', models.DateField(db_index=True, verbose_name='日期')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='名称')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, verbose_name='名称金额')),
            ],
            options={
                'verbose_name': 'pdd_日常记账',
                'verbose_name_plural': 'pdd_日常记账',
                'db_table': 'pdd_day_record',
                'unique_together': {('shop', 'now_date')},
            },
        ),
    ]
