# Generated by Django 4.0.1 on 2022-11-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_pdd_day_record'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdd_day_record',
            unique_together={('shop', 'now_date', 'name')},
        ),
    ]
