# Generated by Django 4.0.1 on 2022-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_pdd_day_record_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='dy_sales',
            name='daren_yongjin',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='达人带货佣金'),
            preserve_default=False,
        ),
    ]
