# Generated by Django 4.0.1 on 2022-12-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_dy_sales_daren_yongjin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dy_sales',
            name='marketing',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='营销费用划扣'),
            preserve_default=False,
        ),
    ]
