# Generated by Django 4.0.1 on 2022-12-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_dy_sales_marketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdd_sales',
            name='budan_yongjin',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20, verbose_name='补单佣金'),
            preserve_default=False,
        ),
    ]
