# Generated by Django 4.0.1 on 2022-12-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_pdd_sales_budan_yongjin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finace_tag_price',
            old_name='famale_tag',
            new_name='female_tag',
        ),
    ]
