# Generated by Django 4.0.1 on 2022-11-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='female_stock',
            fields=[
                ('commodity_code', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, verbose_name='商品编码')),
                ('style_code', models.CharField(db_index=True, max_length=64, verbose_name='款式编码')),
                ('number', models.IntegerField(db_index=True, verbose_name='数量')),
            ],
            options={
                'verbose_name': 'erp_女装临时库存',
                'verbose_name_plural': 'erp_女装临时库存',
                'db_table': 'erp_female_stock',
            },
        ),
        migrations.CreateModel(
            name='male_stock',
            fields=[
                ('commodity_code', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, verbose_name='商品编码')),
                ('style_code', models.CharField(db_index=True, max_length=64, verbose_name='款式编码')),
                ('number', models.IntegerField(db_index=True, verbose_name='数量')),
            ],
            options={
                'verbose_name': 'erp_男装临时库存',
                'verbose_name_plural': 'erp_男装临时库存',
                'db_table': 'erp_male_stock',
            },
        ),
    ]
